# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Items')),
            ],
        ),
    ]
