# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transactionrecords_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecords',
            name='store',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
