# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=20)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
            ],
        ),
    ]
